"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useSession } from "next-auth/react";
type Item={productId:string;name:string;price:number;image:string;quantity:number};
export default function CartPage(){
 const {status}=useSession();const [items,setItems]=useState<Item[]>([]);
 useEffect(()=>{if(status==="authenticated") fetch("/api/cart").then(r=>r.ok?r.json():null).then(d=>{if(d?.items)setItems(d.items.map((x:any)=>({productId:x.productId,name:x.product.name,price:Number(x.product.price),image:x.product.images?.[0]?.url??"",quantity:x.quantity}))});else if(status==="unauthenticated")setItems(JSON.parse(localStorage.getItem("zeno-cart")??"[]"))},[status]);
 async function save(next:Item[]){setItems(next);localStorage.setItem("zeno-cart",JSON.stringify(next));if(status==="authenticated")await fetch("/api/cart",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:next.map(x=>({productId:x.productId,quantity:x.quantity}))})})}
 const total=items.reduce((s,i)=>s+i.price*i.quantity,0);
 return <main className="min-h-screen bg-zinc-950 px-5 py-10 text-white"><div className="mx-auto max-w-5xl"><h1 className="text-4xl font-bold">سلة المشتريات</h1>{status==="loading"?<p className="mt-8">جاري التحميل...</p>:items.length===0?<div className="mt-10 rounded-2xl border border-zinc-800 p-8 text-zinc-400">السلة فاضية. <Link className="text-amber-400" href="/shop">تصفح الساعات</Link></div>:<div className="mt-8 grid gap-8 md:grid-cols-[1fr_320px]"><div className="space-y-4">{items.map(i=><div key={i.productId} className="flex gap-4 rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><img src={i.image} alt="" className="h-24 w-24 rounded-xl object-cover"/><div className="flex-1"><h2>{i.name}</h2><p className="text-zinc-400">{i.price.toLocaleString()} EGP</p><div className="mt-3 flex items-center gap-3"><button onClick={()=>save(items.map(x=>x.productId===i.productId?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>−</button><span>{i.quantity}</span><button onClick={()=>save(items.map(x=>x.productId===i.productId?{...x,quantity:x.quantity+1}:x))}>+</button><button onClick={()=>save(items.filter(x=>x.productId!==i.productId))} className="ml-3 text-red-400">حذف</button></div></div></div>)}</div><aside className="h-fit rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><p className="text-zinc-400">الإجمالي</p><p className="text-3xl font-bold">{total.toLocaleString()} EGP</p><Link href="/checkout" className="mt-6 block rounded-xl bg-amber-400 px-5 py-3 text-center font-bold text-black">إتمام الطلب</Link></aside></div>}</div></main>
}