"use client";

import { FormEvent, useEffect, useState } from "react";

type Coupon={id:string;code:string;discountType:"PERCENTAGE"|"FIXED";discountValue:string|number;isActive:boolean;startsAt:string|null;expiresAt:string|null;minOrderAmount:string|number|null;maxUses:number|null;usedCount:number};
const empty={code:"",discountType:"PERCENTAGE",discountValue:"20",isActive:true,startsAt:"",expiresAt:"",minOrderAmount:"",maxUses:""};

export default function CouponsPage(){
 const [items,setItems]=useState<Coupon[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/coupons",{cache:"no-store"});const d=await r.json();if(r.ok)setItems(d);else setMessage(d.error||"Could not load coupons");}
 useEffect(()=>{load()},[]);
 function reset(){setEditing(null);setForm(empty)}
 async function save(e:FormEvent){e.preventDefault();setMessage("");const body={...form,discountValue:Number(form.discountValue),minOrderAmount:form.minOrderAmount?Number(form.minOrderAmount):null,maxUses:form.maxUses?Number(form.maxUses):null,startsAt:form.startsAt||null,expiresAt:form.expiresAt||null};const r=await fetch("/api/admin/coupons",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{id:editing,...body}:body)});const d=await r.json();if(!r.ok){setMessage(d.error||"Could not save");return}setMessage("Saved.");reset();load()}
 function edit(c:Coupon){setEditing(c.id);setForm({code:c.code,discountType:c.discountType,discountValue:String(c.discountValue),isActive:c.isActive,startsAt:c.startsAt?c.startsAt.slice(0,16):"",expiresAt:c.expiresAt?c.expiresAt.slice(0,16):"",minOrderAmount:c.minOrderAmount==null?"":String(c.minOrderAmount),maxUses:c.maxUses==null?"":String(c.maxUses)})}
 async function deactivate(id:string){await fetch("/api/admin/coupons?id="+id,{method:"DELETE"});load()}
 return <main className="adminPage"><header><p className="eyebrow">PROMOTIONS</p><h1>Coupons</h1><p>Create and manage discount codes.</p></header>{message&&<div className="adminNotice">{message}</div>}
 <section className="adminCard"><div className="editorTitle"><div><h2>{editing?"Edit coupon":"Add coupon"}</h2></div>{editing&&<button className="adminSecondary" onClick={reset}>Cancel</button>}</div>
 <form onSubmit={save} className="adminForm"><label>Code<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="NEW20"/></label><label>Type<select value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value as Coupon["discountType"]})}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed EGP</option></select></label><label>Value<input required type="number" min="0" step="0.01" value={form.discountValue} onChange={e=>setForm({...form,discountValue:e.target.value})}/></label><label>Minimum order<input type="number" min="0" value={form.minOrderAmount} onChange={e=>setForm({...form,minOrderAmount:e.target.value})}/></label><label>Max uses<input type="number" min="1" value={form.maxUses} onChange={e=>setForm({...form,maxUses:e.target.value})}/></label><label>Starts<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Expires<input type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label><label className="checks"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><button className="adminAction full">{editing?"Save changes":"Create coupon"}</button></form></section>
 <section className="adminCard"><div className="editorTitle"><div><h2>Coupon list</h2><p>{items.length} coupons</p></div><button className="adminSecondary" onClick={load}>Refresh</button></div><div className="adminTable"><div className="tableRow tableHead"><span>Code</span><span>Discount</span><span>Usage</span><span>Status</span><span>Actions</span></div>{items.map(c=><div className="tableRow" key={c.id}><strong>{c.code}</strong><span>{c.discountType==="PERCENTAGE"?c.discountValue+"%":Number(c.discountValue).toLocaleString()+" EGP"}</span><span>{c.usedCount}{c.maxUses?"/"+c.maxUses:""}</span><span>{c.isActive?"Active":"Inactive"}</span><span><button onClick={()=>edit(c)}>Edit</button> <button onClick={()=>deactivate(c.id)}>Deactivate</button></span></div>)}</div></section>
 </main>
}
